export const USER_UPLOAD_RECORDING_REQUEST = 'USER_UPLOAD_RECORDING_REQUEST';
export const USER_UPLOAD_RECORDING_SUCCESS = 'USER_UPLOAD_RECORDING_SUCCESS';
export const USER_UPLOAD_RECORDING_FAIL = 'USER_UPLOAD_RECORDING_FAIL';

export const GET_USER_RECORDINGS_BY_USERNAME_REQUEST =
  'GET_USER_RECORDINGS_BY_USERNAME_REQUEST';
export const GET_USER_RECORDINGS_BY_USERNAME_SUCCESS =
  'GET_USER_RECORDINGS_BY_USERNAME_SUCCESS';
export const GET_USER_RECORDINGS_BY_USERNAME_FAIL =
  'GET_USER_RECORDINGS_BY_USERNAME_FAIL';

export const GET_MY_RECORDINGS_REQUEST = 'GET_MY_RECORDINGS_REQUEST';
export const GET_MY_RECORDINGS_SUCCESS = 'GET_MY_RECORDINGS_SUCCESS';
export const GET_MY_RECORDINGS_FAIL = 'GET_MY_RECORDINGS_FAIL';

export const EDIT_MY_RECORDING_REQUEST = 'EDIT_MY_RECORDING_REQUEST';
export const EDIT_MY_RECORDING_SUCCESS = 'EDIT_MY_RECORDING_SUCCESS';
export const EDIT_MY_RECORDING_FAIL = 'EDIT_MY_RECORDING_FAIL';

export const DELETE_MY_RECORDING_REQUEST = 'DELETE_MY_RECORDING_REQUEST';
export const DELETE_MY_RECORDING_SUCCESS = 'DELETE_MY_RECORDING_SUCCESS';
export const DELETE_MY_RECORDING_FAIL = 'DELETE_MY_RECORDING_FAIL';

export const LIKE_RECORDING_REQUEST = 'LIKE_RECORDING_REQUEST';
export const LIKE_RECORDING_SUCCESS = 'LIKE_RECORDING_SUCCESS';
export const LIKE_RECORDING_FAIL = 'LIKE_RECORDING_FAIL';

export const COMMENT_RECORDING_REQUEST = 'COMMENT_RECORDING_REQUEST';
export const COMMENT_RECORDING_SUCCESS = 'COMMENT_RECORDING_SUCCESS';
export const COMMENT_RECORDING_FAIL = 'COMMENT_RECORDING_FAIL';

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';

export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_FAIL = 'EDIT_COMMENT_FAIL';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';

export const GET_POPULAR_RECORDINGS_REQUEST = 'GET_POPULAR_RECORDINGS_REQUEST';
export const GET_POPULAR_RECORDINGS_SUCCESS = 'GET_POPULAR_RECORDINGS_SUCCESS';
export const GET_POPULAR_RECORDINGS_FAIL = 'GET_POPULAR_RECORDINGS_FAIL';
