export const USER_UPLOAD_RECORDING_REQUEST = 'USER_UPLOAD_RECORDING_REQUEST';
export const USER_UPLOAD_RECORDING_SUCCESS = 'USER_UPLOAD_RECORDING_SUCCESS';
export const USER_UPLOAD_RECORDING_FAIL = 'USER_UPLOAD_RECORDING_FAIL';